"""Config setup wizard for `rmig init`.

Builds a per-job TOML file via interactive prompts (or all flags from CLI),
with optional remote-side probing (hash algorithm negotiation, file count /
size preview).

Design choices baked in:
  - One TOML file per job (existing convention; we never modify existing TOMLs)
  - User specifies src/dst manually (no /Volumes auto-enumeration)
  - Storage-medium kind (local / remote-ssh / remote-cloud) chosen by the user
    drives the defaults for `local_cache_in_root`, `transfers`, etc.
  - f-string template emits TOML (zero dep beyond stdlib)
"""
from __future__ import annotations

import os
import re
import shutil
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from . import hashing as hashing_mod
from . import rclone as rclone_mod
from . import verbose as verbose_mod


# --- storage medium classification ---

KIND_LOCAL = "local"
KIND_SSH = "remote-ssh"
KIND_CLOUD = "remote-cloud"
KINDS = [KIND_LOCAL, KIND_SSH, KIND_CLOUD]

# rclone backend type → storage kind
SSH_BACKENDS = {"sftp"}
CLOUD_BACKENDS = {
    "s3", "b2", "gcs", "azureblob", "drive", "dropbox", "onedrive",
    "swift", "wasabi", "filefabric", "hidrive", "mailru", "yandex",
    "icloud", "premiumizeme", "putio", "uptobox", "zoho",
}


@dataclass
class InitOptions:
    name: str = ""
    src: str = ""
    dst: str = ""
    src_kind: str = ""
    dst_kind: str = ""
    hash: Optional[str] = None
    write: str = ""               # output TOML path
    probe: bool = True            # query rclone backend features
    interactive: bool = True
    run_check: bool = False       # exec rmig-check after write
    state_dir: str = "~/.local/share/rclone-migrate"


# --- kind detection ---

def detect_kind(path: str) -> str:
    """Best-effort: classify a path as local / remote-ssh / remote-cloud.

    Local if it's a filesystem path. Remote if `<name>:...`; uses
    `rclone config show <name>` to read the backend type and map it.
    """
    if rclone_mod.is_local(path):
        return KIND_LOCAL
    name = rclone_mod.remote_name(path)
    if not name:
        return KIND_LOCAL
    # Look up the backend type
    try:
        cp = rclone_mod._run(["config", "show", name], check=False)
        m = re.search(r"^type\s*=\s*(\w+)", cp.stdout, re.MULTILINE)
        if m:
            t = m.group(1).lower()
            if t in SSH_BACKENDS:
                return KIND_SSH
            if t in CLOUD_BACKENDS:
                return KIND_CLOUD
    except Exception:
        pass
    # Default for unrecognized remotes
    return KIND_CLOUD


# --- defaults derivation ---

def derive_defaults(src_kind: str, dst_kind: str) -> dict:
    """Pick sensible defaults for [defaults] based on storage kinds."""
    transfers = 4
    if KIND_CLOUD in (src_kind, dst_kind):
        # Cloud backends tolerate more concurrency
        transfers = 8

    # local_cache_in_root: when src is local (likely SD card / ext drive),
    # don't write cache files into source. When dst is local, fine to write.
    local_cache_in_root = False if src_kind == KIND_LOCAL else True

    # download: only true if a remote with no native hash forces it. We default
    # off and let the runtime auto-flip when needed.
    download = False

    return {
        "transfers": transfers,
        "local_cache_in_root": local_cache_in_root,
        "download": download,
    }


# --- TOML rendering ---

def render_toml(opts: InitOptions) -> str:
    d = derive_defaults(opts.src_kind, opts.dst_kind)
    hash_line = (
        f'hash = "{opts.hash}"' if opts.hash
        else '# hash = "SHA256"   # uncomment to force; otherwise auto-negotiated'
    )
    cache_str = "true" if d["local_cache_in_root"] else "false"
    cache_comment = (
        "" if d["local_cache_in_root"]
        else "   # src is local — keep cache off the source disk"
    )
    download_str = "true" if d["download"] else "false"

    return textwrap.dedent(f"""\
        # rclone-migrate job: {opts.name}
        # Generated by `rmig init`. Edit freely.

        [defaults]
        state_dir = "{opts.state_dir}"
        transfers = {d['transfers']}
        local_cache_in_root = {cache_str}{cache_comment}
        download = {download_str}
        {hash_line}

        [delete]
        require_check_within = "24h"
        require_confirm = true
        remove_empty_src_dirs = true

        [[jobs]]
        name = "{opts.name}"
        src  = "{opts.src}"
        dst  = "{opts.dst}"
        # src_kind = "{opts.src_kind}"
        # dst_kind = "{opts.dst_kind}"
        """)


# --- prompts ---

def _prompt(prompt: str, default: Optional[str] = None,
            choices: Optional[List[str]] = None) -> str:
    suffix = f" [{default}]" if default else ""
    if choices:
        suffix += f" ({'/'.join(choices)})"
    while True:
        try:
            ans = input(f"{prompt}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(130)
        if not ans and default is not None:
            ans = default
        if not ans:
            print("  (required)")
            continue
        if choices and ans not in choices:
            print(f"  must be one of: {', '.join(choices)}")
            continue
        return ans


def _confirm(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    try:
        ans = input(f"{prompt} [{d}]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    if not ans:
        return default
    return ans in ("y", "yes")


# --- name slugification ---

def slugify(s: str) -> str:
    """Turn 'Insta360 X5' or '/Volumes/Insta360 X5' into 'insta360-x5'."""
    s = os.path.basename(s.rstrip("/")) or s
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "job"


# --- main wizard flow ---

def collect(opts: InitOptions, v: verbose_mod.Verbose) -> InitOptions:
    """Fill in any missing fields by prompting (or fail in non-interactive)."""
    if not opts.src:
        if not opts.interactive:
            raise ValueError("--src is required in non-interactive mode")
        opts.src = _prompt("Source path or rclone remote (e.g. /Volumes/X or thinkpad:/p)")
    if not opts.dst:
        if not opts.interactive:
            raise ValueError("--dst is required in non-interactive mode")
        opts.dst = _prompt("Destination path or rclone remote")
    if not opts.name:
        suggested = slugify(opts.src)
        if opts.interactive:
            opts.name = _prompt("Job name", default=suggested)
        else:
            opts.name = suggested
    if not opts.src_kind:
        det = detect_kind(opts.src)
        if opts.interactive:
            opts.src_kind = _prompt("src kind", default=det, choices=KINDS)
        else:
            opts.src_kind = det
    if not opts.dst_kind:
        det = detect_kind(opts.dst)
        if opts.interactive:
            opts.dst_kind = _prompt("dst kind", default=det, choices=KINDS)
        else:
            opts.dst_kind = det
    if not opts.write:
        default_path = os.path.expanduser(opts.state_dir) + f"/{opts.name}.toml"
        if opts.interactive:
            opts.write = _prompt("Write TOML to", default=default_path)
        else:
            opts.write = default_path
    return opts


def probe(opts: InitOptions, v: verbose_mod.Verbose) -> Optional[str]:
    """Run rclone backend feature lookup on both sides and negotiate hash.
    Returns the negotiated algorithm name, or None if probe failed/skipped."""
    if not opts.probe:
        return None
    try:
        v.info(f"Probing src ({opts.src}) ...")
        src_h = sorted(hashing_mod.supported_hashes(opts.src))
        v.info(f"  src hashes: {src_h}")
        v.info(f"Probing dst ({opts.dst}) ...")
        dst_h = sorted(hashing_mod.supported_hashes(opts.dst))
        v.info(f"  dst hashes: {dst_h}")
        algo = hashing_mod.negotiate(opts.src, opts.dst, override=opts.hash)
        v.ok(f"  → negotiated hash algorithm: {algo}")
        return algo
    except Exception as e:
        v.warn(f"probe failed: {e}")
        v.warn("  (you can still proceed; rmig-check will fail on the same error)")
        return None


def write_toml(opts: InitOptions, v: verbose_mod.Verbose) -> Path:
    p = Path(os.path.expanduser(opts.write))
    if p.exists():
        if opts.interactive:
            if not _confirm(f"{p} exists; overwrite?", default=False):
                v.warn("aborted")
                sys.exit(1)
        else:
            v.warn(f"{p} exists — overwriting (non-interactive)")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_toml(opts))
    v.ok(f"Wrote {p}")
    return p


def run_init(opts: InitOptions, v: verbose_mod.Verbose) -> int:
    opts = collect(opts, v)

    v.info("")
    v.info("Configuration plan:")
    v.info(f"  job  : {opts.name}")
    v.info(f"  src  : {opts.src}  [{opts.src_kind}]")
    v.info(f"  dst  : {opts.dst}  [{opts.dst_kind}]")
    v.info(f"  TOML : {opts.write}")
    v.info("")

    probe(opts, v)

    rendered = render_toml(opts)
    v.info("Generated TOML:")
    v.info("─" * 60)
    for line in rendered.splitlines():
        v.info(f"  {line}")
    v.info("─" * 60)

    if opts.interactive and not _confirm("Write this file?", default=True):
        v.warn("aborted")
        return 1

    write_toml(opts, v)

    if opts.interactive and _confirm("Run `rmig-check` now?", default=False):
        opts.run_check = True

    if opts.run_check:
        rmig_check = shutil.which("rmig-check") or "rmig-check"
        v.info(f"Exec: {rmig_check} -c {opts.write} -j {opts.name}")
        os.execvp(rmig_check, [rmig_check, "-c", opts.write, "-j", opts.name])

    return 0
